debug = true
description = 'Testserver'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'de'
modules = [ 'js-module', 'js-bytecode-module' ]
name = 'Testserver'
players = 100
port = 7788
resources = [
    'freeroam',
    'nativetuner',
    'charakterEditor'
]
website = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'